// Generated by CoffeeScript 1.6.3
(function() {
  var app, application_root, buildingController, express, nano, path, port;

  application_root = __dirname;

  express = require("../node_modules/express");

  path = require("../node_modules/path");

  nano = require("../node_modules/nano");

  app = express();

  app.configure(function() {
    app.use(express.cookieParser('manny is cool'));
    app.use(express.cookieSession());
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(app.router);
    app.use(express["static"](path.join(application_root, "../public")));
    app.use('/static', express["static"](path.join(application_root, "../static")));
    return app.use(express.errorHandler({
      dumpExceptions: true,
      showStack: true
    }));
  });

  buildingController = require('./controllers/buildings');

  nano = require('nano')('http://localhost:5984');

  app.get("/api", function(request, response) {
    response.header("Content-Type", "application/json");
    return response.send(200, '{ "online" : true }');
  });

  app.get("/api/buildings", buildingController.list);

  app.post("/api/buildings", buildingController.insert);

  app.get("/api/buildings/:id", buildingController.get);

  app.put("/api/buildings/:id", buildingController.insert);

  app.get("/site.manifest", function(request, response, next) {
    response.header("Content-Type", "text/cache-manifest");
    console.log("Site Manifest File was requested");
    return next();
  });

  port = 4000;

  app.listen(port, function() {
    return console.log("Express server listening on port %d in %s mode", port, app.settings.env);
  });

}).call(this);
