// Generated by CoffeeScript 1.6.3
(function() {
  var User;

  User = require('../models/user');

  exports.loginOrNew = function(request, response) {
    var user;
    if ((request.body.email != null) && request.body.email.length > 5) {
      if (request.body.passwordrepeated != null) {
        if (request.body.password === request.body.passwordrepeated) {
          user = new User(request.body.email, request.body.password);
          return user.save(function(error, obj) {
            if (error == null) {
              request.session.user = user.email;
              request.session.authenticated;
              return response.send(200, {
                email: user.email,
                _id: obj.id
              });
            } else {
              return console.log(err);
            }
          });
        } else {
          return response.send('400', 'Retyped password did not match the password.');
        }
      } else {
        user = new User(request.body.email, request.body.password);
        return user.findOne(function(error, dbUser) {
          if (error == null) {
            return user.comparePassword(dbUser.password, function(err, isMatch) {
              if (err == null) {
                if (isMatch != null) {
                  request.session.user = user.email;
                  request.session.authenticated;
                  return response.send(200, {
                    email: dbUser.email,
                    _id: dbUser.id
                  });
                }
              } else {
                return response.send(403);
              }
            });
          } else {
            return response.send(500);
          }
        });
      }
    } else {
      return response.send(400);
    }
  };

}).call(this);
