// Generated by CoffeeScript 1.6.3
(function() {
  var User;

  User = require('../models/user');

  exports.loginOrNew = function(request, response) {
    var user;
    if ((request.body.email != null) && request.body.email.length > 5) {
      if (request.body.passwordrepeated != null) {
        if (request.body.password === request.body.passwordrepeated) {
          user = new User({
            email: request.body.email,
            password: request.body.password
          });
          return user.save(function(err) {
            if (!err) {
              console.log("created new user");
              console.log(user);
              return response.redirect('/');
            } else {
              return console.log(err);
            }
          });
        } else {
          return response.send('400', 'Retyped password did not match the password.');
        }
      } else {
        return User.findOne({
          email: request.body.email
        }, function(err, user) {
          if (typeof error === "undefined" || error === null) {
            request.session.user = user.email;
            request.session.authenticated;
            return response.send(200, {
              email: user.email,
              _id: user._id
            });
          } else {
            return console.log("err");
          }
        });
      }
    } else {
      return response.send(400);
    }
  };

}).call(this);
